### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by grobacz** [AliasIO/Swiftlet#49]
Main index file is missing, no .htaccess file provided either.
After cloning to local server and running composer i can only access /public/ though the url.
The rewrites of url in App class are done server-side and due to no htaccess my server cannot recognize the path layout. Anything other than /public throws 404. 

I can call function from controller by get: ?q=index/other. But still i can`t access any other controller than the one hardcoded as in public/index.php

**Comment by AliasIO** [comment]
The main index file is `public/index.php`. This is not a regular controller, it's the front controller and all traffic is routed through this file, typically using a server side rewrite.

Controllers can be found in `src/HelloWorld/Controllers`. If you create a new controller here you can access it via `?q=<controllername>`. This should work even without rewrites.

You should configure your virtual host so that it has a hostname and the root path points to 'public'. That way you can navigate to '<hostname>/?q=<controllername>' directly without having 'public' in the URL.

I prefer Nginx over Apache which is why there is no `.htaccess` file. However you should be able to use the same rewrite rule (`rewrite ^/(.*)$  /index.php?q=$1`).

Example Nginx configuration:

```
server {
  listen 80 default;
  listen [::]:80 default ipv6only=on;

  server_name swiftlet.local;

  root /srv/swiftlet/public;

  location / {
                index index.php index.html;

                if ( !-e $request_filename ) {
                        rewrite ^/(.*)$  /index.php?q=$1 last;
                }
        }

  location ~ \.php$ {
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_index index.php;
                fastcgi_read_timeout 3600;
                include fastcgi_params;
  }

  access_log /var/log/nginx/swiftlet.access.log;
  error_log  /var/log/nginx/swiftlet.error.log;
}
```

**Comment by grobacz** [comment]
I'm really suprised to see the answer so quickly. Thank you very much for help.

**Comment by AliasIO** [comment]
Cheers. :)
